### ISSUE TITLE
"python  sunrgbd_data.py --gen_v1_data"  gets:    scipy/io/matlab/mio5.py", , in read_var_header   raise ValueError("Did not read any bytes")

### ISSUE THREAD

**Issue by sisrfeng** [facebookresearch/votenet#109]
Hi, is there anyone who met this?

python  sunrgbd_data.py --gen_v1_data
gets this:  
```
Traceback (most recent call last):
  File "sunrgbd_data.py", line 332, in <module>
    save_votes=True, num_point=50000, use_v1=True, skip_empty_scene=False)
  File "sunrgbd_data.py", line 231, in extract_sunrgbd_data
    pc_upright_depth = dataset.get_depth(data_idx)
  File "sunrgbd_data.py", line 70, in get_depth
    return sunrgbd_utils.load_depth_points_mat(depth_filename)
  File "/d/v/sunrgbd/sunrgbd_utils.py", line 196, in load_depth_points_mat
    depth = sio.loadmat(depth_filename)['instance']
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio.py", line 142, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio5.py", line 272, in get_variables
    hdr, next_position = self.read_var_header()
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio5.py", line 219, in read_var_header
    raise ValueError("Did not read any bytes")
ValueError: Did not read any bytes
```
(but there are files in sunrgbd/sunrgbd_trainval/depth)
![Uploading image.png…]()
Many thx!

**Comment by wanggaoping** [comment]
Hello, I met the same problem as you. Have you solved it?

**Comment by YingLv1106** [comment]
why？ There is no train_data_idx.txt and val_data_idx.txt in my sunrgbd_trainval folder.  Do you have any? Can you tell me where you got it?
