### ISSUE TITLE
ImportError: Could not import _ext module.

### ISSUE THREAD

**Issue by mtli77** [facebookresearch/votenet#112]
Hi, team
Thanks for sharing the wonderful project!
I miss this bug:
```
Traceback (most recent call last):
  File "/disk/tia/votenet_v0/pointnet2/pointnet2_utils.py", line 26, in <module>
    import pointnet2._ext as _ext
ImportError: /home/ubuntu/.conda/envs/tia37/lib/python3.7/site-packages/pointnet2-0.0.0-py3.7-linux-x86_64.egg/pointnet2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 159, in <module>
    MODEL = importlib.import_module(FLAGS.model)  # import network module
  File "/home/ubuntu/.conda/envs/tia37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/disk/tia/votenet_v0/models/votenet.py", line 19, in <module>
    from backbone_module import Pointnet2Backbone
  File "/disk/tia/votenet_v0/models/backbone_module.py", line 19, in <module>
    from pointnet2_modules import PointnetSAModuleVotes, PointnetFPModule
  File "/disk/tia/votenet_v0/pointnet2/pointnet2_modules.py", line 21, in <module>
    import pointnet2_utils
  File "/disk/tia/votenet_v0/pointnet2/pointnet2_utils.py", line 30, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst
```
It seems that something goes wrong during the pointnet2 compile.
I use python 3.7, pytorch 1.4.0, cuda 10.0, gcc 7.5.0
Could you please help me to compile with this?

**Comment by giangdip2410** [comment]
Same issue with me, it seem because of pytorch version, I am trying to fix but not yet work

**Comment by jiayaozhang** [comment]
Same issue with me

**Comment by IliasMAOUDJ** [comment]
Downgrading to Pytorch 1.1 and using python 3.6 worked for me.

**Comment by trunc8** [comment]
This may help- https://github.com/facebookresearch/votenet/issues/108#issuecomment-783878066

**Comment by sujeongcha** [comment]
This worked for me.

1. Install the latest version of [Pointnet2_Pytorch](https://github.com/erikwijmans/Pointnet2_PyTorch)
`pip install "git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib"
`
2. Change **pointnet2_utils.py** line 26 to:
`import pointnet2_ops._ext as _ext`

**Comment by husnejahan** [comment]
Hi
I am getting this error:

pip install "git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib" 

Error:
fatal: unable to connect to github.com:
  github.com[0: 140.82.114.3]: errno=Connection timed out

  error: subprocess-exited-with-error
  × git clone --filter=blob:none --quiet git://github.com/erikwijmans/Pointnet2_PyTorch.git /tmp/pip-install-n66o5c6k/pointnet2-ops_3847b29857cd47aaa0027093bb8b37fc did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
