### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by foysalahmed10** [facebookresearch/votenet#123]
Hello Sir,
I was trying to train my own dataset in VoteNet. In my dataset have 3 classes. This dataset was prepared for instance segmentation. I build a new data class(PlantNet), I modify the scannet (scannet_detection_dataset.py and model_util_scannet.py) file. Follow through .. When I start training it showing an error. In this dataset, I don't use any images.

Error:
kept 0 scans out of 3640
kept 0 scans out of 1820
0 0
Traceback (most recent call last):
File "train.py", line 155, in
shuffle=True, num_workers=4, worker_init_fn=my_worker_init_fn)
File "/home/foysal/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 176, in init
sampler = RandomSampler(dataset)
File "/home/foysal/.local/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 66, in init
"value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

Thank you, Sir.

**Comment by 123jyw** [comment]
shuffle=True　Ture改成False 两个都改
