### ISSUE TITLE
ModuleNotFoundError: No module named 'pointnet2._ext'

### ISSUE THREAD

**Issue by clarkkent0618** [facebookresearch/votenet#125]
Traceback (most recent call last):
  File "/root/imvotenet-master_PointNet2_Compiled/pointnet2/pointnet2_utils.py", line 26, in <module>
    import pointnet2._ext as _ext
ModuleNotFoundError: No module named 'pointnet2._ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 158, in <module>
    MODEL = importlib.import_module('imvotenet')
  File "/root/miniconda3/envs/myconda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/imvotenet-master_PointNet2_Compiled/models/imvotenet.py", line 19, in <module>
    from backbone_module import Pointnet2Backbone
  File "/root/imvotenet-master_PointNet2_Compiled/models/backbone_module.py", line 19, in <module>
    from pointnet2_modules import PointnetSAModuleVotes, PointnetFPModule
  File "/root/imvotenet-master_PointNet2_Compiled/pointnet2/pointnet2_modules.py", line 21, in <module>
    import pointnet2_utils
  File "/root/imvotenet-master_PointNet2_Compiled/pointnet2/pointnet2_utils.py", line 30, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst

**Comment by clarkkent0618** [comment]
Just **Downgrade** to pytorch 1.2
