### ISSUE TITLE
KeyError: 'loss'

### ISSUE THREAD

**Issue by 123jyw** [facebookresearch/votenet#153]
When running this statement CUDA_VISIBLE_DEVICES=0 python train.py --dataset scannet --log_dir log_scannet --num_point 40000, 
the following error occurs：**** EPOCH 000 ****
Current learning rate: 0.001000
Current BN decay momentum: 0.500000
2022-04-10 17:22:33.082380
/home/z/anaconda3/envs/v/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/z/anaconda3/envs/v/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
eval mAP: nan
eval AR: nan
Traceback (most recent call last):
  File "train.py", line 334, in <module>
    train(start_epoch)
  File "train.py", line 321, in train
    loss = evaluate_one_epoch()
  File "train.py", line 302, in evaluate_one_epoch
    mean_loss = stat_dict['loss']/float(batch_idx+1)
KeyError: 'loss'

Please help the big guys！！！

**Comment by lschoole** [comment]
Any luck?
