### ISSUE TITLE
sunrgbd dataset perparation

### ISSUE THREAD

**Issue by whuhxb** [facebookresearch/votenet#166]
Hi @likethesky @Celebio @colesbury @pdollar @minqi 

Have you ever met this bug when preparing the dataset? Thanks a lot.

srun -p PV1003q -n 1 -w node15 python sunrgbd_data.py --gen_v1_data
-------------  5051
Traceback (most recent call last):
  File "sunrgbd_data.py", line 326, in <module>
    save_votes=True, num_point=50000, use_v1=True, skip_empty_scene=False)
  File "sunrgbd_data.py", line 202, in extract_sunrgbd_data
    objects = dataset.get_label_objects(data_idx)
  File "sunrgbd_data.py", line 72, in get_label_objects
    return sunrgbd_utils.read_sunrgbd_label(label_filename)
  File "/export/home/hanxiaobing/Documents/PlaneNet_PlaneRCNN/DGCNN_PointNet2/SensatUrban/MAE/PiMAE/Pretrain/data/sunrgbd/sunrgbd_utils.py", line 184, in read_sunrgbd_label
    lines = [line.rstrip() for line in open(label_filename)]
FileNotFoundError: [Errno 2] No such file or directory: './sunrgbd_trainval/label_v1/005051.txt'

**Comment by madinwei** [comment]
@whuhxb , Hi,  from your error message I think the label file 005051.txt is messing. make sure you extracted all the files in the sunrgbd_trainval folder correctly from the Matlab script. assuming you are following the [README.md](https://github.com/facebookresearch/votenet/blob/main/sunrgbd/README.md)
