### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set

### ISSUE THREAD

**Issue by DaLei001** [facebookresearch/votenet#2]
Hi，when I use "python setup.py install" to Compile the CUDA layers for PointNet++， I meet a problem:
`Traceback (most recent call last):
File "setup.py", line 24, in <module>
    "nvcc": ["-O2", "-I{}".format("{}/include".format(_ext_src_root))],
File "/home/dai/.local/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 328, in CUDAExtension
    library_dirs += library_paths(cuda=True)
File "/home/dai/.local/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 393, in library_paths
    paths.append(_join_cuda_home(lib_dir))
File "/home/dai/.local/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 724, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.`

could you tell me how to solve this problem? Please~

**Comment by DaLei001** [comment]
After running `python -c "import torch;print(torch.version.cuda)"`, I get `8.0.61`,

But when I run `nvcc --version`, I get ```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```
Is this because the previously installed cuda8.0 is not uninstalled completely?

Above commends as follow you， the problem still exists.
