### ISSUE TITLE
Demo Problem！

### ISSUE THREAD

**Issue by chenxyyy** [facebookresearch/votenet#56]
when i run the ```  python demo.py```, I met a problem like the flowing. 

> Loaded checkpoint /data/cxy/code/votenet/demo_files/pretrained_votenet_on_sunrgbd.tar (epoch: 180)
Loaded point cloud data: /data/cxy/code/votenet/demo_files/input_pc_sunrgbd.ply
Inference time: 2.057940
Finished detection. 9 object detected.
Traceback (most recent call last):
  File "demo.py", line 104, in <module>
    MODEL.dump_results(end_points, dump_dir, DC, True)
  File "/data/cxy/code/votenet/models/dump_helper.py", line 86, in dump_results
    pc_util.write_oriented_bbox(obbs[objectness_prob>DUMP_CONF_THRESH,:], os.path.join(dump_dir, '%06d_pred_confident_bbox.ply'%(idx_beg+i)))
  File "/data/cxy/code/votenet/utils/pc_util.py", line 421, in write_oriented_bbox
    mesh_list = trimesh.util.concatenate(scene.dump())
  File "/home/WJ2/.conda/envs/cxy/lib/python3.6/site-packages/trimesh/scene/scene.py", line 499, in dump
    for node_name in self.graph.nodes_geometry:
  File "/home/WJ2/.conda/envs/cxy/lib/python3.6/site-packages/trimesh/caching.py", line 88, in get_cached
    value = function(*args, **kwargs)
  File "/home/WJ2/.conda/envs/cxy/lib/python3.6/site-packages/trimesh/scene/transforms.py", line 224, in nodes_geometry
    'geometry' in self.transforms.node[n]):
AttributeError: 'EnforcedForest' object has no attribute 'node'

Can anynoe help me?  Thanks.

**Comment by Violetit** [comment]
> when i run the ` python demo.py`, I met a problem like the flowing. My trimesh edition is 2.35.39.
> 
> > Loaded checkpoint /data/cxy/code/votenet/demo_files/pretrained_votenet_on_sunrgbd.tar (epoch: 180)
> > Loaded point cloud data: /data/cxy/code/votenet/demo_files/input_pc_sunrgbd.ply
> > Inference time: 2.057940
> > Finished detection. 9 object detected.
> > Traceback (most recent call last):
> > File "demo.py", line 104, in 
> > MODEL.dump_results(end_points, dump_dir, DC, True)
> > File "/data/cxy/code/votenet/models/dump_helper.py", line 86, in dump_results
> > pc_util.write_oriented_bbox(obbs[objectness_prob>DUMP_CONF_THRESH,:], os.path.join(dump_dir, '%06d_pred_confident_bbox.ply'%(idx_beg+i)))
> > File "/data/cxy/code/votenet/utils/pc_util.py", line 421, in write_oriented_bbox
> > mesh_list = trimesh.util.concatenate(scene.dump())
> > File "/home/WJ2/.conda/envs/cxy/lib/python3.6/site-packages/trimesh/scene/scene.py", line 499, in dump
> > for node_name in self.graph.nodes_geometry:
> > File "/home/WJ2/.conda/envs/cxy/lib/python3.6/site-packages/trimesh/caching.py", line 88, in get_cached
> > value = function(*args, **kwargs)
> > File "/home/WJ2/.conda/envs/cxy/lib/python3.6/site-packages/trimesh/scene/transforms.py", line 224, in nodes_geometry
> > 'geometry' in self.transforms.node[n]):
> > AttributeError: 'EnforcedForest' object has no attribute 'node'
> 
> Can anynoe help me? Thanks.

It is caused by networkx,  follow this solution:
https://github.com/facebookresearch/votenet/issues/40#issuecomment-549525021

**Comment by chenxyyy** [comment]
Thank you very much! I have solved this question. @Violetit

**Comment by ai-starter** [comment]
I meet the same problem. I do not know why. I open the result by meshlab, but the result is not have the box. 

Constructed model.
Loaded checkpoint /home/votenet-master/demo_files/pretrained_votenet_on_sunrgbd.tar (epoch: 180)
Loaded point cloud data: /home/votenet-master/demo_files/input_pc_sunrgbd.ply
Inference time: 0.138507
Finished detection. 9 object detected.
Traceback (most recent call last):
  File "demo.py", line 101, in <module>
    MODEL.dump_results(end_points, dump_dir, DC, True)
  File "/home/votenet-master/models/dump_helper.py", line 86, in dump_results
    pc_util.write_oriented_bbox(obbs[objectness_prob>DUMP_CONF_THRESH,:], os.path.join(dump_dir, '%06d_pred_confident_bbox.ply'%(idx_beg+i)))
  File "/home/votenet-master/utils/pc_util.py", line 421, in write_oriented_bbox
    mesh_list = trimesh.util.concatenate(scene.dump())
  File "/usr/local/lib/python3.6/dist-packages/trimesh/scene/scene.py", line 499, in dump
    for node_name in self.graph.nodes_geometry:
  File "/usr/local/lib/python3.6/dist-packages/trimesh/caching.py", line 88, in get_cached
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trimesh/scene/transforms.py", line 224, in nodes_geometry
    'geometry' in self.transforms.node[n]):
AttributeError: 'EnforcedForest' object has no attribute 'node'

It is the same problem with the fist. Can anyone help me ? thanks @chenxyyy
