### ISSUE TITLE
Problem with demo.py

### ISSUE THREAD

**Issue by wechwang** [facebookresearch/votenet#67]
When I run the ` python demo.py`, I got a problem:

(jupyterlab) root@ca0155a0f759:/home/jupyterlab/votenet# python demo.py
Constructed model.
Traceback (most recent call last):
  File "/usr/local/envs/jupyterlab/lib/python3.6/tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: "t'[]u'[]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/jupyterlab/lib/python3.6/tarfile.py", line 2297, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/local/envs/jupyterlab/lib/python3.6/tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/local/envs/jupyterlab/lib/python3.6/tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "/usr/local/envs/jupyterlab/lib/python3.6/tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/jupyterlab/lib/python3.6/site-packages/torch/serialization.py", line 556, in _load
    return legacy_load(f)
  File "/usr/local/envs/jupyterlab/lib/python3.6/site-packages/torch/serialization.py", line 467, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/local/envs/jupyterlab/lib/python3.6/tarfile.py", line 1589, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/local/envs/jupyterlab/lib/python3.6/tarfile.py", line 1619, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/local/envs/jupyterlab/lib/python3.6/tarfile.py", line 1482, in __init__
    self.firstmember = self.next()
  File "/usr/local/envs/jupyterlab/lib/python3.6/tarfile.py", line 2309, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 76, in <module>
    checkpoint = torch.load(checkpoint_path)
  File "/usr/local/envs/jupyterlab/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/envs/jupyterlab/lib/python3.6/site-packages/torch/serialization.py", line 560, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: /home/jupyterlab/votenet/demo_files/pretrained_votenet_on_sunrgbd.tar is a zip archive (did you mean to use torch.jit.load()?)

What should I do?

**Comment by wechwang** [comment]
Problem solved.
I use my own checkpoint and point cloud instead of the pre-trained models and sample point clouds.
