### ISSUE TITLE
undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by Prominem** [facebookresearch/votenet#70]
When I try to run this code, I face this error.
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    MODEL = importlib.import_module(FLAGS.model) # import network module
  File "/home/aistudio/external-libraries/votenet/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/aistudio/work/votenet/models/votenet.py", line 19, in <module>
    from backbone_module import Pointnet2Backbone
  File "/home/aistudio/work/votenet/models/backbone_module.py", line 19, in <module>
    from pointnet2_modules import PointnetSAModuleVotes, PointnetFPModule
  File "/home/aistudio/work/votenet/pointnet2/pointnet2_modules.py", line 21, in <module>
    import pointnet2_utils
  File "/home/aistudio/work/votenet/pointnet2/pointnet2_utils.py", line 24, in <module>
    import pointnet2._ext as _ext
ImportError: /home/aistudio/external-libraries/votenet/lib/python3.6/site-packages/pointnet2-0.0.0-py3.6-linux-x86_64.egg/pointnet2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration

My machine's system has cuda-9.2. I compile and run this code on conda virtual environment with cudatoolkit-9.0, cudnn-7.6.5. Could someone solve this problem? thanks a lot.

**Comment by Zhixinli2887** [comment]
You met the same issue and I reinstall python 3.6, all done.
