### ISSUE TITLE
votenet can't work in pytorch1.4.0

### ISSUE THREAD

**Issue by houlili1357-9** [facebookresearch/votenet#91]
When I change the pytorch to 1.4.0, it can't work, the error is:

[root@localhost votenet]# python models/votenet.py 
Traceback (most recent call last):
  File "/home/hll/hllhome/code/votenet/pointnet2/pointnet2_utils.py", line 26, in <module>
    import pointnet2._ext as _ext
ImportError: /home/hll/miniconda3/envs/pytorch14/lib/python3.7/site-packages/pointnet2-0.0.0-py3.7-linux-x86_64.egg/pointnet2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "models/votenet.py", line 19, in <module>
    from backbone_module import Pointnet2Backbone
  File "/home/hll/hllhome/code/votenet/models/backbone_module.py", line 19, in <module>
    from pointnet2_modules import PointnetSAModuleVotes, PointnetFPModule
  File "/home/hll/hllhome/code/votenet/pointnet2/pointnet2_modules.py", line 21, in <module>
    import pointnet2_utils
  File "/home/hll/hllhome/code/votenet/pointnet2/pointnet2_utils.py", line 30, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst

**Comment by sumo-agarwal** [comment]
Hello! 

I am facing the same issue. Could you resolve the issue?

**Comment by houlili1357-9** [comment]
If you replace all the pointnet++ net from C++ code to python, the issue can be solved, but the efficiency will be low.
If you don't want to change the code, you should work in pytorch1.1 and tensorflow1.4.

**Comment by sumo-agarwal** [comment]
Thanks for the clarification. I was able to import the code in pytorch 1.4 but suffered with  indefinite or null values in the weight matrix during training.

**Comment by shangzhouye** [comment]
> If you replace all the pointnet++ net from C++ code to python, the issue can be solved, but the efficiency will be low.
> If you don't want to change the code, you should work in pytorch1.1 and tensorflow1.4.

@houlili1357-9 

Hi, could I ask what do you mean by replacing all the pointnet++ net from C++ code to python and how can I do that?

Thank you.
